### ISSUE TITLE
[BUG]Can't parse Firebase public RS256 keys

### ISSUE THREAD

**Issue by xy4455** [GlitchedPolygons/l8w8jwt#3] opened 2020-05-12 08:10 UTC
**Describe the bug**
I'm trying to validate a JWT token generated by Firebase. It seems l8w8jwt can't parse the public keys provided to validate the signature.

`params.alg = L8W8JWT_ALG_RS256;`

The public keys are provided here: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com

**To Reproduce**

**Expected behavior**
Public keys parses correctly 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MaOS 10.15.4

**Additional context**

Certificate provided below

-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIA/oH1w0GNmMwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMjAw\nNDI3MDkxOTU2WhcNMjAwNTEzMjEzNDU2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAJ0JeaPobguFV56+uzblHTomAFVcixD2fyERU4x618fxuTRq\nEBCZErH3SeUIR0KH8KIbjBYcF8DVZLF0xWSAIhVCbcp1t+53ICri4uWrh6VI0vvl\nsj0u5zB1r26UYfbAv3vyV8ImbfjFra2JUnWs+zzf102X2cD0CiFnG5qXWQnEoGdg\nY0GbAH+AMjH4Pt9W+aohZ+LpZXjakjPaqF1x61pTy0ApHOrHnprzDxd13jIansoj\nHO4fphkxBJiiXBaCuWrexrLdPJZiYtyuimuMtVBTPnIfFJye8uMB8zV0F6STeSYg\nYDmWcAbyRViyivcoyxQZh/A1WdEV9VmhpltqaZ0CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBABnHr4qQhoXG9T93ChoyhKvY8dFEe0FPUcUT6zaJxR4F\nuXahQtUEIzXdLZ9ADStMMePNJRj8kAEvwPIyioKppV/AF6Y/Ea8XHm7KNvY+c8FA\nI7lBbfg9azJcrtZGQsSbTuowTQZX1R1jBq1FWZ/bxwn6vnIU75LaYBk5lB2HbwCL\ny4RmHAX73BLPtVnmR3WdI6eUbSt4IPI4FzpLGonwI50vi2bnCTI22OkVtucr8nAh\noXEG+FPAiStqwMaHr8v2I68dAgNk97aQWVULrxZm/LjFh4A+FLK6FpGgITLpbp+I\nzlhFewXrAFp8Up6U3Sch6SCXrtEjDfkyhHbb/j+RtYI=\n-----END CERTIFICATE-----\n

**Comment by GlitchedPolygons** [comment] 2020-05-12 09:31
Can you please check if the decode function returns L8W8JWT_KEY_PARSE_FAILURE?
Looking at the provided pub key, I can see a trailing '\n' character: MbedTLS does not support that for some reason. You need to trim that manually before parsing. Let me know if it was that :)

**Comment by xy4455** [comment] 2020-05-12 11:01
Hi, thanks. I does return L8W8JWT_KEY_PARSE_FAILURE. I've tried a few permutations of the key already, 

This is my current (using C++11 raw string literals). There is no new-line at the end.

One thing I did notice, the header and footer are different than what seems to expected, stepping through the code I see checks for ```----BEGIN PUBLIC KEY-----` and `-----BEGIN RSA PUBLIC KEY-----` but never `-----BEGIN CERTIFICATE-----```. However, modifying my key to have one of those headers only postpones the problem. The key still won't parse.


```
auto key = R"(
-----BEGIN CERTIFICATE-----
MIIDHDCCAgSgAwIBAgIIVKzVWRoMU5UwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE
AxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMjAw
NTA1MDkxOTU2WhcNMjAwNTIxMjEzNDU2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl
bi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAOckfYh1/aaqMN8bqvoeDUailhwMUrWUw0wOknS2HLzNUaV1
LJf0HM3IQ7xBh0W+Obe1HTGNLR/Hp8G1hPKAIdpuGJjmVdNDIg2vm99X1MPi5cXN
qF9n9JO0l9KeMkkyslGIEuujYuvDXtcgK9FrdN8xxX+eb6N5aqzQSh88TaAJ+JBQ
AwCIzo2GtdNukVePBH99xCiyMdEFX5yNfK/t6criT2740fekVRw/Si1XmBE2d+Ul
tiQFuRBLH4XWy46Zb44oGkfgLmzvnQqQh/aF8NXB47TfOa+JeLgj8rnHn3LFgTkr
kq0q7AuJheofpMzCDCYJd79Eo9/rhN2EAgtY2fUCAwEAAaM4MDYwDAYDVR0TAQH/
BAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ
KoZIhvcNAQEFBQADggEBAB8VhDLUgN6dNiMqs4sevFKQpixCtN8yg6qiRRMtaPQN
88VETVPXh5acaN83UOOfwtTFZWyZxpSSlWbTI/1E9JJB0GCQX2T7LKm57jHSEeQ9
mI5ybpRxlm2Jvt7n5sAFHNADSbIdFNEtnGQmh9NVdwe8Zcrzl1NALgeFtiHgvVAe
uUtKehM+YxK4daNifpkO/e4PNFWgbLJpZtdcG+z+v7DH/9Fwv0JG+Z1RkXjD32iu
iDun3U2W4C7QSnh9cOCbapfkMsXjSA9NvCqUzk1FdnqS9fd8szc389QZGZqQw8WU
hT9c2fShPT13vgZfNj7fpU2EGBoa3Zu6ybck5pzi0dE=
-----END CERTIFICATE-----)";
```

**Comment by GlitchedPolygons** [comment] 2020-05-12 11:06
That's... strange.
And yes, the key parse function is suboptimal, I agree. That's something that comes from the crypto library though. 

I hope I can find a solution to this as soon as I have the time.

**Comment by xy4455** [comment] 2020-05-12 11:14
Thanks for that, I really appreciate the effort you are taking to make a non dependency lib for dealing with JWT. 

I'm pretty sure that by removing the `\n` and changing the headers and footer I managed to nudge my key through the superficial checks, however at that point it started interpreting the key and I guess something was going wrong there. But I don't know how to fix that.

Btw, I had to make some small trivial changes (added a few casts) to compile the headers using C++17 and AppleClang 11. Are you interested in those changes?

**Comment by GlitchedPolygons** [comment] 2020-05-12 11:31
> 
> 
> Thanks for that, I really appreciate the effort you are taking to make a non dependency lib for dealing with JWT.

Thank you for the kind words! :)
I'm glad this is useful to you.

> 
> I'm pretty sure that by removing the `\n` and changing the headers and footer I managed to nudge my key through the superficial checks, however at that point it started interpreting the key and I guess something was going wrong there. But I don't know how to fix that.

I'm starting to wonder if that key type is even supported by MbedTLS's crypto engine (I for instance had issues importing the certificate into Kleopatra too, which uses neither l8w8jwt nor MbedTLS code).

> Btw, I had to make some small trivial changes (added a few casts) to compile the headers using C++17 and AppleClang 11. Are you interested in those changes?

I'm sorry, I really want this lib to stay C-only and compiler-independent, let's not mix languages (at least not at the library level ;) 
But you can obviously fork this and apply the changes there. Just make sure to state the modifications as per the Apache-2.0 license somewhere, e.g. in the README.md file or inside the headers directly :)
If you isolate your C++ specific headers away into separate-enough directories, submit a PR and I'll look at it for sure. Maybe we can still work out a solution if it's _really_ just the headers

**Comment by xy4455** [comment] 2020-05-12 11:39
Actually, now I think about it, it might just have been changes to the example, for instance I had to change into this:
```
params.validate_iss = (char *)"Black Mesa"; 
params.validate_sub = (char *) "Gordon Freeman";
```

But you are completely right, keeping the library C only makes a lot of sense.

So I guess it is not looking so good for my key then :-(

**Comment by GlitchedPolygons** [comment] 2020-05-12 11:49
That's too bad :\
Do you have control over the key type that your backend provides you? Maybe try to enforce a classic RSA key (4096-bit if possible)?

Sorry btw I'm curious: is that cast necessary in your situation?

**Comment by xy4455** [comment] 2020-05-12 11:59
>Do you have control over the key type that your backend provides you? Maybe try to enforce a classic RSA key (4096-bit if possible)?

None at all, I'm connecting against firebase, and they only use RS256, with those two public keys. 

It seems the cast is required, here is a similar change in `chillbuf.h`:
original:
`char* error_msg = malloc(error_length * sizeof(char));` 
Compiler error: `chillbuff.h:130:11: error: cannot initialize a variable of type 'char *' with an rvalue of type 'void *'`

Whereas this is fine:
`char* error_msg = (char *) malloc(error_length * sizeof(char));`

**Comment by GlitchedPolygons** [comment] 2020-05-12 12:12
Ahw, well, yeah.. In C++ that is indeed mandatory when using `malloc`, since it can't implicitly cast that `void*`. I didn't think about that when originally writing this :P
The cast is not necessary in C.
About the keys again: you got me curious. I'll do some research as soon as I have the time. I'm leaving this issue open for now. Thanks for informing about this issue! 👍  :)

**Comment by xy4455** [comment] 2020-05-12 12:14
Yeah... well it's not a big thing thankfully :-) 

Great, thanks for leaving it open. Let's see what you find out. Please let me know if I can help.

**Comment by xy4455** [comment] 2020-05-26 11:38
So I've been doing some digging on my own, and I had all sorts of trouble parsing the public key using OpenSSL too. Until it dawned on me, those are not public keys, it is a certificate which _contains_ a public key. So at least I can get to the key now using OpenSSL, still need to do the signature verification.

But anyway, I thought you would like to know. It seems mbedtls would support parsing a x509 certificate, but I haven't really looked at it yet.

**Comment by GlitchedPolygons** [comment] 2020-05-26 11:56
> So I've been doing some digging on my own, and I had all sorts of trouble parsing the public key using OpenSSL too. Until it dawned on me, those are not public keys, it is a certificate which _contains_ a public key. So at least I can get to the key now using OpenSSL, still need to do the signature verification.
> 
> But anyway, I thought you would like to know. It seems mbedtls would support parsing a x509 certificate, but I haven't really looked at it yet.

Thanks so much for this!

I sadly haven't had the time yet (I'm currently relocating, and my new home office is basically still a room full of cardboard boxes LOL). 

But I should've guessed it too... The `BEGIN CERTIFICATE` PEM-header kinda gave it away ;D
Now that I see it......


As soon as I have the time I'll look into the mbedtls x.509 support (thanks for pointing that out!). The ideal result would be to have l8w8jwt detect the `BEGIN CERTIFICATE` header and automatically let mbedtls parse as x.509 instead of pub key.

**Comment by xy4455** [comment] 2020-05-26 12:11
> But I should've guessed it too... The BEGIN CERTIFICATE PEM-header kinda gave it away ;D
Now that I see it......

Hahaha yes, in retrospect we should have noticed. It was in all caps too :-D 

Good luck with moving, I understand other issues will have priority. 

If you could provide me with some pointers I don't mind having a quick go at it, if I find the time.

**Comment by GlitchedPolygons** [comment] 2020-05-26 12:22
> Good luck with moving, I understand other issues will have priority.

Thank you :)

> If you could provide me with some pointers I don't mind having a quick go at it, if I find the time.

Sure thing. 
The interesting part is definitively 
[Line 315 of decode.c](https://github.com/GlitchedPolygons/l8w8jwt/blob/d996fa13e195896a2c04d33d076fe30a50463a1d/src/decode.c#L315). That's where the key is loaded into mbedtls. Simply checking if the header is BEGIN CERTIFICATE should be enough imho. I'm imagining an if statement and some mbedtls_parse_certificate() function, which would then extract the pubkey from the cert. Let me know if you have a better idea though :)

**Comment by xy4455** [comment] 2020-05-26 15:37
So... good news and bad. The signature is verified! 

I did something like this inside decode.c. It is still missing some cleanup etc, and it might need to make its way into the PSXXX cases too.
```
            case L8W8JWT_ALG_RS256:
            case L8W8JWT_ALG_RS384:
            case L8W8JWT_ALG_RS512:
                if (keyIsCertificate)
                {
                    mbedtls_x509_crt crt;
                    mbedtls_x509_crt_init(&crt);
                    r = mbedtls_x509_crt_parse(&crt, key, key_length);
                    if (r != 0)
                    {
                        r = L8W8JWT_KEY_PARSE_FAILURE;
                        goto exit;
                    }
                    r = mbedtls_pk_verify(&crt.pk, md_type, hash, md_length, (const unsigned char*)signature, signature_length);
                    if (r != 0)
                    {
                        r |= L8W8JWT_SIGNATURE_VERIFICATION_FAILURE;
                        goto exit;
                    }
                }
                else
```

Should I make a branch and push my changes for your consideration? 

The bad news is that I'm getting some parse issues on the token itself  :-( Which I really don't understand because the token looks fine when I manually process the Json in another lib or online at https://www.jsonwebtoken.io. I hate going too much of-topic, but perhaps you can give me a quick pointer? A dummy token string is below, this is what I'm passing into `params.jwt`. Again sorry for that, but I'm really kind of stuck.
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcHJvai1jLWE2NGY4IiwiYXVkIjoicHJvai1jLWE2NGY4IiwiYXV0aF90aW1lIjoxNTkwNTA1MzA0LCJ1c2VyX2lkIjoibjFsSUhPT3hMUGdGYlNJRVl5TmVkYURqb2M0MyIsInN1YiI6Im4xbElIT094TFBnRmJTSUVZeU5lZGFEam9jNDMiLCJpYXQiOjE1OTA1MDUzMDQsImV4cCI6MTU5MDUwOTM3OSwiZW1haWwiOiJkdW1teXVzZXJAbm9zdWNoZG9tYWluLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJkdW1teXVzZXJAbm9zdWNoZG9tYWluLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn0sImp0aSI6IjM1YjMzYmRiLTI1YjQtNDUwOS05NGQ2LTZmNzAxNzhjNDM2ZSJ9.A7KMjR1AktdW7jkCNRGThW-SzSy9K4mqGILHcJFFfM8
```

**Comment by GlitchedPolygons** [comment] 2020-05-26 20:12
> 
> 
> So... good news and bad. The signature is verified!
> 
> I did something like this inside decode.c. It is still missing some cleanup etc, and it might need to make its way into the PSXXX cases too.
> 
> ```
>             case L8W8JWT_ALG_RS256:
>             case L8W8JWT_ALG_RS384:
>             case L8W8JWT_ALG_RS512:
>                 if (keyIsCertificate)
>                 {
>                     mbedtls_x509_crt crt;
>                     mbedtls_x509_crt_init(&crt);
>                     r = mbedtls_x509_crt_parse(&crt, key, key_length);
>                     if (r != 0)
>                     {
>                         r = L8W8JWT_KEY_PARSE_FAILURE;
>                         goto exit;
>                     }
>                     r = mbedtls_pk_verify(&crt.pk, md_type, hash, md_length, (const unsigned char*)signature, signature_length);
>                     if (r != 0)
>                     {
>                         r |= L8W8JWT_SIGNATURE_VERIFICATION_FAILURE;
>                         goto exit;
>                     }
>                 }
>                 else
> ```
> 
> Should I make a branch and push my changes for your consideration?

Thanks for the snippet! I felt the urge and quickly allocated some time to implement this + some cleanup + unit tests. See commit 60b2def for more details. The tests pass with keys that I externally generated with OpenSSL for every key type and algo variant 😃 

I'll close this issue, but feel free to re-open it at any time if you find issues with the implementation.

> 
> The bad news is that I'm getting some parse issues on the token itself :-( Which I really don't understand because the token looks fine when I manually process the Json in another lib or online at https://www.jsonwebtoken.io. I hate going too much of-topic, but perhaps you can give me a quick pointer? A dummy token string is below, this is what I'm passing into `params.jwt`. Again sorry for that, but I'm really kind of stuck.
> 
> ```
> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcHJvai1jLWE2NGY4IiwiYXVkIjoicHJvai1jLWE2NGY4IiwiYXV0aF90aW1lIjoxNTkwNTA1MzA0LCJ1c2VyX2lkIjoibjFsSUhPT3hMUGdGYlNJRVl5TmVkYURqb2M0MyIsInN1YiI6Im4xbElIT094TFBnRmJTSUVZeU5lZGFEam9jNDMiLCJpYXQiOjE1OTA1MDUzMDQsImV4cCI6MTU5MDUwOTM3OSwiZW1haWwiOiJkdW1teXVzZXJAbm9zdWNoZG9tYWluLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJkdW1teXVzZXJAbm9zdWNoZG9tYWluLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn0sImp0aSI6IjM1YjMzYmRiLTI1YjQtNDUwOS05NGQ2LTZmNzAxNzhjNDM2ZSJ9.A7KMjR1AktdW7jkCNRGThW-SzSy9K4mqGILHcJFFfM8
> ```

Now, about this...

The example token you pasted is of type HS256, and the parsing failure would be a separate issue to inspect, which has no correlation to the signature verification key/certificate (this issue).

Maybe open a new issue or [PM me directly](mailto:info@glitchedpolygons.com) with some more detailed infos for repro and code snippets?
I'd suggest opening an issue, so other people can learn from this too :)
Just make sure to not include any actually relevant keys/tokens in any form: generate fresh test keys that are discardable and describe the phenomenon so I can reproduce it.

**Closed by GlitchedPolygons** 2020-05-26 20:12 UTC
Labels: bug

**Comment by xy4455** [comment] 2020-05-27 07:30
Thanks for that. I just pulled in the changes and can confirm the signature verification works! 

That leaves the other issue. I'll file a new bug for the other issue.
